export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINR_PROYECTO_ACTUAL = 'ELIMINR_PROYECTO_ACTUAL';
export const PROYECTO_ERROR = ' PROYECTO_ERROR';

export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const AUTH_REGISTRO_EXITO = 'AUTH_REGISTRO_EXITO';
export const AUTH_REGISTRO_ERROR = 'AUTH_REGISTRO_ERROR';
export const AUTH_OBTENER_USUARIO = 'AUTH_OBTENER_USUARIO';
export const AUTH_LOGIN_EXITO = 'AUTH_LOGIN_EXITO';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_CERRAR_SESION = 'AUTH_CERRAR_SESION';
